java -Dlogging.level=ON -cp csvjdbc-1.0-37.jar;HashRelMap-0.0.1-SNAPSHOT-jar-with-dependencies.jar client.Ddsloader ^
-licensekey KloadNG92-2L52-OYMS-V5VU-6H8R-O7TS-STLP-I61A ^
-sourcequery "SELECT userid as userid_dot_SAMP_, age as age_dot_SAMP_, EventId as EventId_dot_SAMP_, channel as channel_dot_SAMP_, breuserid as breuserid_dot_SAMP_, brecontext as brecontext_dot_SAMP_ FROM GetNextBestContent" ^
-sourcereadintervalinimillisecs 5000 ^
-targethttpmethod "GET" ^
-targetdataformat "JSON" ^
-tablekeys "tablekey[0][0]=return userid;SAMP" ^
-sourcedburl "jdbc:relique:csv:." ^
-sourcedriver "org.relique.jdbc.csv.CsvDriver" ^
-sourceusername "jdbc_source_username" ^
-sourceuserpassword "jdbc_source_password" ^
-targetkeys userid ^
-targeturl "http://132.145.65.68:8080/bre/getdata?userid=~userid~&age=~age~&breuserid=~breuserid~&channel=~channel~&brecontext=~brecontext~" ^
-targetdbtable data.ddstest_11b6429df8735b13d70808652d560be2 ^
-targetusername dnode_ext ^
-targetpassword dnode_ext ^
-dbfetchsize 1 ^
-bulkloaderthreads 1 ^
-setdatasources "top_ eq SAMP" ^
-setcolumnmappings "userid eq USERID;age eq AGE;channel eq CHANNEL;breuserid eq BREUSERID;brecontext eq BRECONTEXT"
pause